// Generates .design-sync/styles.css from @hiro/ui-tokens (cssVariablesFor + themes).
// Reproducible: re-run after any theme/token change so the synced CSS never drifts.
//   node .design-sync/gen-css.mjs
import { build } from "esbuild";
import { writeFileSync } from "fs";
import path from "path";

const repo = process.cwd();
const entry = `
export { cssVariablesFor } from ${JSON.stringify(path.join(repo, "packages/ui-tokens/src/css.ts"))};
export { themes } from ${JSON.stringify(path.join(repo, "packages/ui-tokens/src/themes.ts"))};
`;

const res = await build({
  stdin: { contents: entry, resolveDir: repo, loader: "ts" },
  bundle: true,
  format: "esm",
  write: false,
  platform: "node",
});
const code = res.outputFiles[0].text;
const mod = await import("data:text/javascript;base64," + Buffer.from(code).toString("base64"));
const { cssVariablesFor, themes } = mod;

const themeIds = Object.keys(themes); // aurora, daylight, superchore, neon
const DEFAULT = "aurora";

const fontImport =
  "@import url('https://fonts.googleapis.com/css2?" +
  "family=Inter:wght@400;500;600;700;800&" +
  "family=Manrope:wght@400;500;600;700;800&" +
  "family=Press+Start+2P&" +
  "family=Rajdhani:wght@400;500;600;700&" +
  "family=Exo+2:wght@400;500;600;700&" +
  "family=IBM+Plex+Mono:wght@400;500&" +
  "family=JetBrains+Mono:wght@400;500&display=swap');";

function block(selector, vars) {
  const lines = Object.entries(vars).map(([k, v]) => `  ${k}: ${v};`);
  return `${selector} {\n${lines.join("\n")}\n}`;
}

const parts = [
  "/* Generated by .design-sync/gen-css.mjs from @hiro/ui-tokens — do not hand-edit. */",
  fontImport,
  "",
  "/* Default theme: Aurora (dark). The design agent renders at :root unless [data-theme] is set. */",
  block(":root", cssVariablesFor(DEFAULT)),
  "",
  block(
    "html, body",
    {
      "background": "var(--hiro-color-bg)",
      "color": "var(--hiro-color-ink)",
      "font-family": "var(--hiro-font-family)",
    }
  ),
  "",
  "/* Per-theme overrides — set data-theme on <html> to switch. */",
  ...themeIds.map((id) => block(`[data-theme="${id}"]`, cssVariablesFor(id))),
  "",
];

// Lives inside packages/ui-tokens/: pulled in via cfg.tokensPkg + cfg.tokensGlob
// (the @hiro/ui-tokens node_modules symlink). Under packages/ui-tokens/ it is
// lint-exempt (isTokenSource), which is correct — this IS the tokens-as-CSS.
// Gitignored — regenerated from this committed script, so it never drifts.
const out = path.join(repo, "packages/ui-tokens/.design-sync-theme-vars.css");
writeFileSync(out, parts.join("\n") + "\n");
console.log("wrote", out, "— themes:", themeIds.join(", "));
